const DATA_GRID = [
	{
		id: 1,
		name: "New Zealand",
		link: "/galleries/new-zealand",
		img: "url(/images/new-zealand.jpg)",
	},
	{
		id: 2,
		name: "Mountain",
		link: "/themes/mountain",
		img: "url(/images/mountain.jpg)",
	},
	{
		id: 3,
		name: "Lake",
		link: "/themes/lake",
		img: "url(/images/lake.jpg)",
	},
	{
		id: 4,
		name: "Africa",
		link: "/galleries/africa",
		img: "url(/images/africa.jpg)",
	},
	{
		id: 5,
		name: "Australia",
		link: "/galleries/australia",
		img: "url(/images/australia.jpg)",
	},
	{
		id: 6,
		name: "Oceanic",
		link: "/themes/oceanic",
		img: "url(/images/oceanic.jpg)",
	},
	{
		id: 7,
		name: "Panoramic",
		link: "/galleries/panoramic",
		img: "url(/images/panoramic.jpg)",
	},
	{
		id: 8,
		name: "Europe",
		link: "/galleries/europe",
		img: "url(/images/europe.jpg)",
	},
	{
		id: 9,
		name: "Urban",
		link: "/themes/urban",
		img: "url(/images/urban.jpg)",
	},
	{
		id: 10,
		name: "Wildlife",
		link: "/themes/wildlife",
		img: "url(/images/wildlife.jpg)",
	},
	{
		id: 11,
		name: "Sunset",
		link: "/themes/sunset",
		img: "url(/images/sunset.jpg)",
	},
	{
		id: 12,
		name: "Waterfall",
		link: "/themes/waterfall",
		img: "url(/images/waterfall.jpg)",
	},
	{
		id: 13,
		name: "Black & White",
		link: "/themes/b&w",
		img: "url(/images/bnw.jpg)",
	},
]
export default DATA_GRID

/*const data = [
	{
		id: 1,
		name: "New Zealand",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ1",
		img: "url(/images/new-zealand.jpg)",
		path: "/images/new-zealand.jpg",
		route: "/galleries/new-zealand",
		categorie: "New Zealand",
		gallery: "Gallery",
	},
	{
		id: 2,
		name: "Mountain",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ2",
		img: "url(/images/mountain.jpg)",
		path: "/images/mountain.jpg",
		route: "/themes/mountain",
		categorie: "Mountain",
		gallery: "Theme",
	},
	{
		id: 3,
		name: "Lake",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ3",
		img: "url(/images/lake.jpg)",
		path: "/images/lake.jpg",
		route: "/themes/lake",
		categorie: "Lake",
		gallery: "Theme",
	},
	{
		id: 4,
		name: "Africa",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ4",
		img: "url(/images/africa.jpg)",
		path: "/images/africa.jpg",
		route: "/galleries/africa",
		categorie: "Africa",
		gallery: "Gallery",
	},
	{
		id: 5,
		name: "Australia",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ5",
		img: "url(/images/australia.jpg)",
		path: "/images/australia.jpg",
		route: "/galleries/australia",
		categorie: "Australia",
		gallery: "Gallery",
	},
	{
		id: 6,
		name: "Ocean",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ6",
		img: "url(/images/ocean.jpg)",
		path: "/images/ocean.jpg",
		route: "/themes/ocean",
		categorie: "Ocean",
		gallery: "Theme",
	},
	{
		id: 7,
		name: "Panoramic",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ7",
		img: "url(/images/panoramic.jpg)",
		path: "/images/panoramic.jpg",
		route: "/themes/panoramic",
		categorie: "Panoramic",
		gallery: "Theme",
	},
	{
		id: 8,
		name: "Europe",
		location: "Istanbul, Turquie",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ8",
		img: "url(/images/europe.jpg)",
		path: "/images/europe.jpg",
		route: "/galleries/europe",
		categorie: "Europe",
		gallery: "Gallery",
	},
	{
		id: 9,
		name: "Urban",
		location: "New Zealand",
		description:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
		link: "/product/NZ9",
		img: "url(/images/urban.jpg)",
		path: "/images/urban.jpg",
		route: "/themes/urban",
		categorie: "Urban",
		gallery: "Theme",
	},
]*/
